Fix error when running `//:clang-format` target
Running target `//:clang-format` would fail due to:

  ERROR: action 'Copying files' is not up-to-date

where the out of date file was due to:

  SUBCOMMAND: # @llvm_16_0_toolchain//:clang-format [action 'Copying
  files', configuration:
  9fc8a8262f58c1d22b9ca8421b92460c8b557b748071184ec95e106048b61999,
  execution platform: @local_config_platform//:host]

This commit updates `@bazel_clang_format` so it not longer fails if
the clang-format binary target is not up-to-date.

Change-Id: I19bfc3146f6bdc454f94581bf303cb44535967b4